name: Vault Demo

on:
    workflow_dispatch:

jobs:
    echo-vault-secret:
        runs-on: ubuntu-latest
        steps:
            - name: Testing Secrets
              run: |
                if [[ -z "${{secrets.AWS_API_KEY }}" ]]; then
                   echo "Secrets Not Found"
                   exit 1
                else
                    echo "Secrets Found"
                    exit 0
                fi